AllCops:
  NewCops: enable
  Excludes:
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "config/**/*"
    - "node_modules/**/*"
    - "config.ru"
    - "Rakefile"
    - "test/**/*"
Style/Documentation:
    Enabled: false
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
MethodLength:
  CountComments: true  # count full line comments?
  Max: 19
Metrics/AbcSize:
  Max: 20 