default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password:
  timeout: 5000

development:
  <<: *default
  database: resume_maker_development

test:
  <<: *default
  database: resume_maker_test

production:
  <<: *default
  database: resume_maker_production
